
/**
 * @file   src/global.c
 * @author Dionysios Diamantopoulos(diamantd@microlab.ntua.gr)
 * @date   December 2013
 *
 * @brief  Memluv global variables, i.e. core, freelist etc.
 */

#include "memluv.h"
#include "global.h"
#include "gen_memluv_wrappers.h"

/** HW heaps and MemluvAlloc/MemluvFree wrappers are automated generated by gen_memluv_wrappers.c, included in ../build/memluv_wrappers.c */
#include "../build/memluv_wrappers.c"

/** This static struct holds some of the configuration of MemLuv. Is is declared as static here, since global.c is embodied directly in memluv.c 
 *(no separated object is generated and linked) 
 */
static MemLuvConf MemLuvConf0 = {
.num_hw_heaps = NUM_HW_HEAPS,
.dbg_fd = NULL
};

#if HW_DEBUG_MEMLUV==1
MemLuvStats ReturnMemLuvStats(void) {
	return (MemLuvCore0.stats);
}
#endif

MemLuvCore *ReturnMemLuvCore(void) {
	return (&MemLuvCore0);
}

